name: Deploy to Neocities

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build static site
        uses: jerryjvl/jekyll-build-action@v1

      - name: Deploy to Neocities using Ruby CLI
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: public
